
version: 2

sources:
    - name: telco_martech_data
      description: "A starter dbt model"
      database: protean-garage-368913
      schema: telco_martech_data
      table:
          - name: input
