
version: 2

sources:
    - name: telco_martech_data
      description: "A slightly modified sourc input.csv file ato accept weird format of date type as string"
      database: protean-garage-368913
      schema: telco_martech_data
      table:
          - name: input
      columns:
          - name: msisdn
            tests:
                - unique 
                - not null
          - name: subscr_id
            tests:
                - unique 
                - not null
          - name: email_address                     
            tests:
                - unique 
                - not null

models:
    - name: stg_customer_details
      description: "Staging model of the input file"
    
    - name: analytics
      description: "Data model for the analyses"
